language: csharp
mono: none
dotnet: 3.1.411
solution: ReactApplication.sln
before_script:
  - dotnet restore
script:
  - dotnet build ReactApplication.sln -c Release
  #- dotnet test ReactApplication.Tests/ReactApplication.Tests.csproj
  - dotnet test BLL.Test/BLL.Test.csproj
  # "sbt clean coverage test"
   
after_success: "sbt coveralls"
