language: csharp
mono: none
dotnet: 3.1.411
solution: ReactApplication.sln
before_script:
  - dotnet restore
script:
  - dotnet build ReactApplication.sln -c Release
  - dotnet test ReactApplication.Tests/ReactApplication.Tests.csproj
  #- dotnet test ./ReactApplication.Tests-c Release -f netcoreapp3.1.411

  #- dotnet test ReactApplication.Tests/ReactApplication.Tests.csproj -f netcoreapp2.1
 # - dotnet test BLL.Test/BLL.Test.csproj -f netcoreapp2.1
  #mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
